echo Waiting for Mod Manager to close...
ping -n 2 127.0.0.1 >nul
echo Replacing outdated files with updated ones...
copy *.* "../" /y >nul
echo Running Mod Manager...
start "" "../Outer Wilds Mod Manager.exe"
echo Exiting updater...
exit
